# Generated by Django 4.2.3 on 2023-07-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae', models.IntegerField()),
                ('activity', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('duration', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('discipline', models.CharField(max_length=255)),
                ('uk_credit', models.IntegerField()),
                ('us_credit', models.IntegerField()),
                ('fheq_level', models.IntegerField()),
                ('date_approved', models.DateField()),
                ('core_attributes', models.CharField(max_length=255)),
                ('pre_requisites', models.CharField(max_length=255)),
                ('co_requisites', models.CharField(max_length=255)),
                ('overview', models.TextField(null=True)),
                ('learning_outcomes', models.TextField(null=True)),
                ('teaching_learning', models.TextField(null=True)),
                ('assessment_desc', models.TextField(null=True)),
                ('feedback', models.TextField(null=True)),
                ('readings', models.TextField(null=True)),
                ('topics', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_with_prereq', to='docprocessing.course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq', to='docprocessing.course')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('K', 'Knowledge and Understanding'), ('S', 'Subject Specific Skills'), ('J', 'Transferable and Employability Skills')], max_length=1)),
                ('text_desc', models.TextField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docprocessing.course')),
            ],
        ),
        migrations.CreateModel(
            name='Coreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coreq', to='docprocessing.course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_with_coreq', to='docprocessing.course')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.IntegerField()),
                ('date_approved', models.DateField()),
                ('date_published', models.DateField()),
                ('owner', models.CharField(max_length=100)),
                ('next_review_date', models.DateField()),
                ('mod_cat_num', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docprocessing.course')),
            ],
        ),
    ]
