# Generated by Django 4.2.3 on 2023-07-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('discipline', models.CharField(max_length=255)),
                ('uk_credit', models.IntegerField()),
                ('us_credit', models.IntegerField()),
                ('fheq_level', models.IntegerField()),
                ('date_approved', models.DateField()),
                ('core_attributes', models.CharField(max_length=255)),
                ('pre_requisites', models.CharField(max_length=255)),
                ('co_requisites', models.CharField(max_length=255)),
            ],
        ),
    ]
