# Generated by Django 4.2.3 on 2023-07-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
