# Generated by Django 4.2.3 on 2023-07-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_approved',
            field=models.CharField(max_length=255),
        ),
    ]
