# Generated by Django 4.2.3 on 2023-07-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0002_templates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Assessment',
        ),
        migrations.RenameField(
            model_name='templates',
            old_name='assignment_key',
            new_name='assessment_key',
        ),
        migrations.AlterUniqueTogether(
            name='templates',
            unique_together={('version', 'assessment_key', 'course_code')},
        ),
    ]
