# Generated by Django 4.2.3 on 2023-07-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0003_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assessment_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='readings',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_learning',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.TextField(null=True),
        ),
    ]
