# Generated by Django 4.2.3 on 2023-07-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0002_alter_course_date_approved'),
        ('docprocessing', '0003_rename_assignment_assessment_and_more'),
    ]

    operations = [
    ]
