# Generated by Django 4.2.3 on 2023-07-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0005_prereq_learningoutcomes_coreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.IntegerField()),
                ('date_approved', models.DateField()),
                ('date_published', models.DateField()),
                ('owner', models.CharField(max_length=100)),
                ('next_review_date', models.DateField()),
                ('mod_cat_num', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docprocessing.course')),
            ],
        ),
    ]
