# Generated by Django 4.2.3 on 2023-07-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0005_alter_learningoutcomes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
