# Generated by Django 4.2.3 on 2023-07-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0006_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='approval_status',
            field=models.IntegerField(choices=[(0, 'Denied'), (1, 'Pending'), (2, 'Approved')], default=1, verbose_name='Approval Status'),
        ),
    ]
