# Generated by Django 4.2.3 on 2023-07-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0006_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproversTeamplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docprocessing.approver')),
                ('templateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docprocessing.templates')),
            ],
        ),
    ]
