# Generated by Django 4.2.3 on 2023-07-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0007_approversteamplates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApproversTeamplates',
            new_name='ApproversTemplates',
        ),
    ]
