# Generated by Django 4.2.3 on 2023-07-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0007_templates_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='approvers',
            field=models.CharField(default='', max_length=255),
        ),
    ]
