# Generated by Django 4.2.3 on 2023-07-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0008_templates_approvers'),
        ('docprocessing', '0008_templates_status'),
    ]

    operations = [
    ]
