# Generated by Django 4.2.3 on 2023-07-29 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0008_rename_approversteamplates_approverstemplates'),
        ('docprocessing', '0008_templates_status'),
    ]

    operations = [
    ]
