# Generated by Django 4.2.3 on 2023-07-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0009_merge_20230729_2353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApproversTemplates',
            new_name='ApproverTemplate',
        ),
        migrations.RenameModel(
            old_name='LearningOutcomes',
            new_name='LearningOutcome',
        ),
        migrations.RenameModel(
            old_name='Templates',
            new_name='Template',
        ),
        migrations.AddField(
            model_name='approver',
            name='hashed_email',
            field=models.CharField(default='defaultvalue', max_length=255),
            preserve_default=False,
        ),
    ]
