# Generated by Django 4.2.3 on 2023-07-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessing', '0009_merge_0008_templates_approvers_0008_templates_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='approval_status',
        ),
    ]
